2023 02 01 bhargav add stack trace
RoboTutorLLC/RoboTutor_2020 pull request #127
Opened 2023-02-05 08:44 UTC by bhargavmyadam

1)Dumped stack trace in existing postError function previously just for stack-tracing CRASH.
2) Implemented error log creation similar to crash logs for each ERROR. All the ERROR_log.txt files are being stored in Robotutor_ERROR directory. --> don't want to have to change DriveSync FOLDER PAIRS on tablets.  Options:
a. Dump directly to same folder as crash_logs.
b. Make robotutor_error folder under crash_logs.
c. Make robotutor_error folder under tablet top-level RoboTutor folder where logs go and get uploaded. --> DO THIS

ERROR_LOG filepath and filename format:
path:  [device storage, e.g. /storage/emulated/0]/RoboTutor/RoboTutor_ERROR/
filename:  ERROR_RoboTutor_version_device ID _session sequence number_ session start time_error time_"sanitized" error message

"sanitize" = start...end or #hash

      java.lang.ClassCastException: cmu.xprize.robotutor.tutorengine.widgets.core.TStudentProfileModal cannot be cast to cmu.xprize.robotutor.tutorengine.ITutorObject

--------- Stack trace ---------

    cmu.xprize.robotutor.tutorengine.CTutor.mapChildren(CTutor.java:740)
    cmu.xprize.robotutor.tutorengine.CTutor.automateScene(CTutor.java:707)
    cmu.xprize.robotutor.tutorengine.CTutor.instantiateScene(CTutor.java:682)
    cmu.xprize.robotutor.tutorengine.CTutorGraph.gotoNextScene(CTutorGraph.java:448)
    cmu.xprize.robotutor.tutorengine.CTutorGraph$Queue.run(CTutorGraph.java:203)
    android.os.Handler.handleCallback(Handler.java:938)
    android.os.Handler.dispatchMessage(Handler.java:99)
    android.os.Looper.loop(Looper.java:223)
    android.app.ActivityThread.main(ActivityThread.java:7656)
    java.lang.reflect.Method.invoke(Native Method)
    com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
    com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
-------------------------------

--------- Cause ---------

-------------------------------

2023-02-08 17:19 UTC, JackMostow requested changes
change file folder and filename as discussed
leave newlines in error .txt for readability

2023-02-14 18:17 UTC, JackMostow approved these changes
Looks fine.  Thanks! - Jack

2023-02-14 18:18 UTC, JackMostow approved these changes

2023-02-14 18:19 UTC, JackMostow approved these changes

2023-02-14 18:47 UTC, JackMostow requested changes
1. lines 325ff:  (How) does e.StackTrace differ from cause.StackTrace?
2. Please include milliseconds in timestamps by appending .SSS
3. line 358:  please uncomment RoboTutor.SEQUENCE_ID_STRING + "_" + if you can find where it's defined.  It's the 6-digit session sequence number that survives the dreaded clock reset.
4. Please include session start time in error filename to facilitate retrieval of session log from the error log name.
Thanks!

2023-02-15 16:58 UTC, JackMostow submitted a review, later dismissed

2023-02-15 17:16 UTC, JackMostow approved these changes

2023-02-15 17:16 UTC, JackMostow approved these changes

2023-02-15 17:17 UTC, JackMostow approved these changes

2023-02-15 17:18 UTC, JackMostow approved these changes

2023-02-15 17:20 UTC, JackMostow submitted a review, later dismissed

2023-02-20 04:57 UTC, JackMostow commented
@bhargavmyadam and everyone I cc'd in case this problem affected you:

The build failed before because travis started charging for builds for private repos, so I made robotutor_2020 public -- which required first making https://github.com/judithodili/RoboTutor_Help_Intervention and https://github.com/kevindeland/RoboTutor public.  
The reason is that a repo can't be made public if it’s forked from a private repository.  [https://github.com/RoboTutorLLC/RoboTutor_2020](https://github.com/RoboTutorLLC/RoboTutor_2020/settings) was forked from https://github.com/judithodili/RoboTutor_Help_Intervention, which was private and forked from https://github.com/kevindeland/RoboTutor, which was also private.   (For details, see https://github.com/orgs/community/discussions/22624).  Kevin and Judith kindly agreed to make those repos public.

In case you’re wondering why now, it’s because we build our apks using https://app.travis-ci.com/Builds, which just announced that “Builds have been temporarily disabled for private repositories due to a negative credit balance.”  I hope that making our repo public solved the problem.  

@bhargavmyadam - Please try the travis build again to confirm that it works now, and let us know either way.  Thanks!  - Jack

2023-02-20 13:26 UTC, madeleinvillegas commented
@JackMostow Travis is still not working for the same reason (negative credit balance) even if the repo is already public. I think the credit limit is present regardless of whether he repo is public or private.

2023-02-22 16:41 UTC, JackMostow approved these changes
Dummy commit to test if Travis does builds now.

2023-02-22 16:45 UTC, merged

2023-02-22 16:46 UTC, JackMostow commented
Travis builds are working again; did a dummy commit to trigger this one.